
exports_files([
	"Intents.mobileprovision",
	"NotificationContent.mobileprovision",
	"NotificationService.mobileprovision",
	"Share.mobileprovision",
	"Iosapp.mobileprovision",
	"WatchApp.mobileprovision",
	"WatchExtension.mobileprovision",
	"Widget.mobileprovision",
	"BroadcastUpload.mobileprovision",
])
